language: node_js
node_js:
- '10'
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_f70af52dfb93_key -iv $encrypted_f70af52dfb93_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan $SERVER >> ~/.ssh/known_hosts
- git remote add deploy dokku@$SERVER:$APP_NAME
- git config --global push.default simple
- git push deploy master -f
branches:
  only:
  - master
